# coding = 'utf-8'
'''
Created on 2023年4月25日
@author: autotest
'''
eiTlvSelDict={
    'CMAC_dlUeTtiInfo':{
        'ACK':True,
        'AMC':True,
        'BSRCHANGE':True,
        'CFG':True,
        'CFG_FAIL_INF':True,
        'CSI':True,
        'DL_PDU':True,
        'DL_SCHD_TASK':True,
        'LCH_SCHD':True,
        'PUCCH_PC':True,
        'SCHD':True,
        'SCHD_FAIL_RSN':True,
        'TA':True
        },
    'CMAC_ulUeTtiInfo':{
        'AMC':True,
        'BSR':True,
        'CFG':True,
        'CRCI':True,
        'ERROR_IND':True,
        'GRANT':True,
        'MSG1':True,
        'PHR':True,
        'PHY_MGR_TASK':True,
        'PUCCH':True,
        'PUSCH_SINR':True,
        'SCHD_FAIL_RSN':True,
        'SLOT_DISC':True,
        'SLOT_INT':True,
        'SR':True,
        'SRS':True,
        'SRS_PMI':True,
        'SR_PMI':True,
        'SR_MAX':True,
        'UL_PDU':True,
        'UL_SCHD_TASK':True
        },
    'PHY_dlCellInfo':{
        'Param':True
        },
    'PHY_pbchTtiInfo':{
        'CSIRS':True,
        'PB':True
        },
    'PHY_pdcchTtiInfo':{
        'Coreset':True,
        'Pdcch':True
        },
    'PHY_pdschTtiInfo':{
        'Param':False
        },
    'PHY_prachTtiInfo':{
        'Param':True
        },
    'PHY_pucchTtiInfo':{
        'Param':False,
        'Rpt':False
        },
    'PHY_puschTtiInfo':{
        'Param':True
        },
    'PHY_ulCellInfo':{
        'Param':True
        },
    'RLC_ulUeTtiInfo':{
        'CCCH':True,
        'CELL_Kpi':True,
        'SRB_UL_SEND_TO_CP':True,
        'UL_DATA_PDU':False,
        'UL_STATUS_PDU':True,
        'UL_STATUS_TIME_COST':True,
        'UL_TB_TIME_COST':True,
        },
    'RLC_dlUeTtiInfo':{
        'DL_ASSEM_INFO':True,
        'DL_DATA_PDU':True,
        'DL_STATUS_PDU':False,
        'MSG4':True,
        'PAGING':True,
        'RLF_INFO':False,
        'SI':True,
        'SIB1':True,
        'SRB_RCV_FROM_CP':True,
        'SSB':True
        }
    }
