# coding = utf-8 
'''
Created on 2022年9月6日

@author: dj
'''
URL_DICT={
    'login':
    {
        'action':'/api/uiframe/v1/login Content-Type:application/json',
        'method':'POST',
        'header':{
            'content-type': "application/json; charset=UTF-8",
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; warningFlag=false'
        },
        'body':{
            'isEncypted':'true',
            'username':'root',
            'password':'hms123...',
            'vcode':'app'
        }
    },
    'queryVersionInfo':
    {
        'action':'/api/hmsCfg/v1/queryPageEnbWithVersionInfoByCondition',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'domainList':'1,2,3,5,7,9,11,13,15,17,19,21,23,25,27,3,5,7,9,11,13,15,17,19,21,2,3,5,7,9,11,13,15,17,19,21,23,25,273,25,27',
            'enbName':'',
            'serialNumber':'',
            'enbIp':'',
            'enbStatus':'',
            'region':'',
            'start':0,
            'limit':100
        }
    },
    'queryEnbSoftwareVersionFromDeviceBySns':
    {
        'action':'/api/hmsCfg/v1/queryEnbSoftwareVersionFromDeviceBySns',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "enbSns":["902272840016"]
            }
    },
    'downloadVersion':
    {
        'action':'/api/hmsCfg/v1/software/download',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'snList':[''],
            'softVersion':''
        }
    },
    'findPageDownloadTask':
    {
        'action':'/api/hmsCfg/v1/software/findPageDownloadTask',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"MultiUE4.9G-BT",
            "enbIp":"",
            "softVersion":"",
            "opStatus":"",
            "startTime":"",
            "endTime":"",
            "start":0,
            "limit":100
        }
    },
    'queryPageEnbByCondition4SoftwareDownload':
    {
        'action':'/api/hmsCfg/v1/software/queryPageEnbByCondition4SoftwareDownload',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "downloadVersion":"",
            "start":0,
            "limit":100
        },
    },
    'activeVersion':
    {
        'action':'/api/hmsCfg/v1/software/batchActivate',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'snList':[''],
        }
    },
    'findPageActivateTask':
    {
        'action':'/api/hmsCfg/v1/software/findPageActivateTask',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"MultiUE4.9G-BT",
            "enbIp":"",
            "softVersion":"",
            "opStatus":"",
            "startTime":"",
            "endTime":"",
            "start":0,
            "limit":100
        }
    },
    'rollbackVersion':
    {
        'action':'/api/hmsCfg/v1/software/batchRollback',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'snList':[''],
        }
    },
    'findPageRollbackTask':
    {
        'action':'/api/hmsCfg/v1/software/findPageRollbackTask',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"MultiUE4.9G-BT",
            "enbIp":"",
            "softVersion":"",
            "opStatus":"",
            "startTime":"",
            "endTime":"",
            "start":0,
            "limit":100
        }
    },
    'batchRealtimeQuerySoftwareCtrlParameters':
    {
        'action':'/api/hmsCfg/v1/batchRealtimeQuerySoftwareCtrlParameters',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "enbList":[
                {
                    "enbId":141,
                    "placeId":1,
                    "enbIp":"193:168:6:0:100:700:0:1",
                    "connectionRequestUrl":"http://[193:168:6:0:100:700:0:1]:30005/",
                    "serialNumber":"902170700189",
                    "modelName":"BS5514",
                    "enbName":"baocai_new",
                    "enbStatus":0,
                    "enbLock":0,
                    "upStatus":0,
                    "softVersion":"BS5514_V1.10.60C1",
                    "hardVersion":"01.01.01.01.01",
                    "threeGPPSpecVersion":"TR181",
                    "specVersion":"",
                    "hardwarePlatform":"NXP",
                    "alarmStatus":2,
                    "manufacturer":"CHANGKUN",
                    "oui":"7C8334",
                    "creatTime":"2022-09-14 16:06:03",
                    "describes":"",
                    "delAccount":2,
                    "additionalSoftwareVersion":"",
                    "onLineTime":"2022-09-14 16:06:15",
                    "productClass":"L5W6-BS",
                    "wifiVersion":"",
                    "phyVersion":"",
                    "fpgaVersion":"",
                    "region":"",
                    "remark":"System Domain",
                    "domainName":""
                }
            ]
        }
    },
    'queryPageEnbByCondition4SoftwareRollback':
    {
        'action':'/api/hmsCfg/v1/software/queryPageEnbByCondition4SoftwareRollback',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "start":0,
            "limit":100
        }
    },
    'queryCellStatus':
    {
        'action':'/api/hmsCfg/v1/findPageCuCellStatus',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"",
            "enbIp":"",
            "serialNumber":"",
            "region":"",
            "cellActiveState":"",
            "enbStatus":"",
            "start":0,
            "limit":100
        },
    },
    'updateDUCellBasic':
    {
        'action':'/api/hmsCfg/v1/updateDUCellBasic',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "enbId":21,
            "fapInstanceId":"1",
            "duCellBasicId":"1662540106391-1927208069",
            "cellId":"1",
            "nrDuCellName":"nrcell",
            "cellRadius":"500",
            "phyCellID":"133",
            "nRARFCNDL":"723324",
            "nRARFCNUL":"723324",
            "trackingAreaId":"0",
            "ssbFreqPos":"8752",
            "ssbTimePos":"128",
            "freqBandIndList":"79",
            "uLBandwidth":"12",
            "dLBandwidth":"12",
            "duplexMode":"1",
            "subcarrierSpacing":"1",
            "cyclicPrefix":"0",
            "slotAssignment":"2",
            "specialSlotStructure":"44",
            "taOffset":"1",
            "cellAdminState":"0",
            "ssbPeriodicityServingCell":"2",
            "sib1Period":"0",
            "ssbDescMethod":"1",
            "celAvailableState":"0",
            "smtcPeriod":"2",
            "smtcDuration":"3",
            "ranNotificationAreaId":"65535",
            "epre":"-15",
            "prachConfigurationIndex":"147",
            "zeroCorrelationZoneConfig":"7",
            "gpsOutClkDelWaitTime":"2592000"
        },
    },
    'realtimeQueryDuCellBasicByEnbId':
    {
        'action':'/api/hmsCfg/v1/realtimeQueryDuCellBasicByEnbId?enbId=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'findDuCellBasicByEnbId':
    {
        'action':'/api/hmsCfg/v1/findDuCellBasicByEnbId?enbId=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'batchRealTimeQueryCuCellStatus':
    {
        'action':'/api/hmsCfg/v1/batchRealTimeQueryCuCellStatus',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "cuCellIdentifierList":[{
                "enbId":16,
                "cuCellInstanceId":1
            }]
        },
    },
    'queryPageEnbByCondition':
    {
        'action':'/api/hmsCfg/v1/queryPageEnbByCondition',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,3,5",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "start":0,
            "limit":100
        },
    },
    'findCuCellBasicByEnbId':
    {
        'action':'/api/hmsCfg/v1/findCUCellBasicByEnbId?enbId=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'updateCUCellBasic':
    {
        'action':'/api/hmsCfg/v1/updateCUCellBasic',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "cuCellBasicId":"16625316903451085107142",
            "enbId":31,
            "fapInstanceId":"1",
            "cellId":"0",
            "cellName":"nrcell",
            "cuFrequencyBand":"79",
            "duplexMode":"1",
            "userLabel":"hlt",
            "cellActiveState":"0",
            "cellAvailableState":"0"
        },
    },
    'findPageSoftWareInfo':
    {
        'action':'/api/hmsCfg/v1/findPageSoftWareInfo?softVersion=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'reboot':
    {
        'action':'/api/hmsCfg/v1/rebootAsync?enbIdStr=',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'uploadSoft':
    {
        'action':'/api/hmsCfg/v1/uploadSoft?fileSize=',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            'manufacturer':'',
            'softVersion':'',
            'model':'',
            'descInfo':'',
        },
    },
    'uploadDataFileXml':
    {
        'action':'/api/hmsCfg/v1/uploadDataFileXml',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
            "enbId":15,
            "placeId":1,
            "enbIp":"193:168:6:0:200::1",
            "connectionRequestUrl":"http://[193:168:6:0:200::1]:30005/",
            "serialNumber":"902272840007",
            "modelName":"BS5514",
            "enbName":"Automatic-18",
            "enbStatus":0,
            "enbLock":0,
            "upStatus":0,
            "softVersion":"BS5514_V1.10.80P1",
            "hardVersion":"01.01.01.01.04",
            "threeGPPSpecVersion":"TR181",
            "specVersion":"",
            "hardwarePlatform":"NXP",
            "alarmStatus":2,
            "manufacturer":"CHANGKUN",
            "oui":"7C8334",
            "creatTime":"2022-11-03 15:23:56",
            "describes":"自动化测试V4",
            "delAccount":2,
            "additionalSoftwareVersion":"",
            "onLineTime":"2022-11-09 16:10:02",
            "productClass":"L5W6-BS",
            "wifiVersion":"",
            "phyVersion":"",
            "fpgaVersion":"",
            "region":"",
            "remark":"System Domain",
            "domainName":""
        }],
    },
    'queryPageEnbWithDataFileSyncStatusByCondition':
    {
        'action':'/api/hmsCfg/v1/queryPageEnbWithDataFileSyncStatusByCondition',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27,4,5,7,8",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "delAccount":"",
            "start":0,
            "limit":100
        },
    },
    'findEnbDataFile':
    {
        'action':'/api/hmsCfg/v1/findEnbDataFile?enbId=',
        'method':'GET',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
        },
    },
    'downloadXmlFileToLocal':
    {
        'action':'/api/httpfs/v1/download?',
        'method':'GET',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
        },
    },
    'uploadXmlDataFile':
    {
        'action':'/api/hmsCfg/v1/uploadDataFile?',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
        },
    },
    'queryPageDataFile':
    {
        'action':'/api/hmsCfg/v1/queryPageDataFile',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "domainList":"1,3,5",
            "enbName":"",
            "enbIp":"",
            "serialNumber":"",
            "enbStatus":"",
            "dataFileActivateStatus":"",
            "delAccount":"",
            "start":0,
            "limit":100
        }
    },
    'deleteDataFileByIds':
    {
        'action':'/api/hmsCfg/v1/deleteDataFileByIds',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[
            "1668048369485872874821"
        ]
    },
    'downloadDataFileToGnb':
    {
        'action':'/api/hmsCfg/v1/downloadDataFile',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
            "dataId":"1667987649609-1854837404",
            "serialNumber":"902272840007",
            "fileName":"Automatic-18_902272840007_20221109184508.cfg"
        }],
    },
    'pingDiagnose':
    {
        'action':'/api/hmsCfg/v1/pingDiagnose',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "pingTimes":"20",
            "ipList":["195:168:16:0:200:500:0:1"]
        },
    },
    'getHmsReponse':
    {
        'action':'/api/softwarenotification/v1/connect',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
                "channel":"/meta/connect",
                "connectionType":"long-polling",
                "id":"185",
                "clientId":"9qw724rxzyjar3m1o18s9osp6g"
        }],
    },
    'queryClientId':
    {
        'action':'/api/softwarenotification/v1/handshake',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
            "version":"1.0",
            "minimumVersion":"0.9",
            "channel":"/meta/handshake",
            "supportedConnectionTypes":["long-polling","callback-polling"],
            "advice":{"timeout":60000,"interval":0},
            "id":"1"
        }],
    },
    'bandClientId':
    {
        'action':'/api/softwarenotification/v1/',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
            "channel":"/meta/subscribe",
            "subscription":"/enb/diagnose",
            "id":"2",
            "clientId":"bk1p6up2b85qedz1smmjcwj47x3k"
        }],
    },
    'traceRouteDiagnose':
    {
        'action':'/api/hmsCfg/v1/traceRouteDiagnose',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "taskId":"",
            "ipList":["195:168:16:0:200:200:0:1"]
        },
    },
    'validateSoftPolicyCfg':
    {
        'action':'/api/hmsCfg/v1/validateSoftPolicyCfg',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "policyCfgId":"1687754495810", #时间戳
            "policyName":"auto", #策略名
            "policyStatus":"0", # 0-suspend  1-active
            "executeOrNot":"", #
            "downloadFlag":"1",# 0-no download 1-download
            "softVersion":"BS5514_V1.20.20", #版本号
            "triggerMode":"0",# 0-time 1-event
            "times":"2023-06-26 11:40",# download time
            "triggerType":"",#下载触发类型 
            "startTime":"", #触发起时间
            "endTime":"", #触发终时间
            "activateType":"1",# 激活类型  0-不激活  1-下载后激活   2--时间激活
            "timerActivateTime":"",#激活时间
            "creatTime":"",#创建时间
            "creatorID":"65bb5097-de07-44f7-ad5d-20cb413f60de"#创建id
        },
    },#{"success":true}
    'insertSoftPolicyCfg':
    {
        'action':'/api/hmsCfg/v1/insertSoftPolicyCfg',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "policyCfgId":"1687754495810",
            "policyName":"auto",
            "policyStatus":"0",
            "executeOrNot":"",
            "downloadFlag":"1",
            "softVersion":"BS5514_V1.20.20",
            "triggerMode":"0",
            "times":"2023-06-26 11:40",
            "triggerType":"",
            "startTime":"",
            "endTime":"",
            "activateType":"1",
            "timerActivateTime":"",
            "creatTime":"",
            "enbPolicyCfgs":[
                {"serialNumber":"902133550090","triggerMode":0},
                {"serialNumber":"902133550089","triggerMode":0}
            ],
            "creatorID":"65bb5097-de07-44f7-ad5d-20cb413f60de"
        },
    },#{"result":true}
    'findPageSoftwareUpgradePolicy':
    {
        'action':'/api/hmsCfg/v1/findPageSoftwareUpgradePolicy',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "policyName":"",
            "policyStatus":"",
            "triggerMode":"",
            "executeOrNot":"",
            "operatorID":"65bb5097-de07-44f7-ad5d-20cb413f60de",
            "rootUserFlag":True,
            "operatorUserName":"root",
            "start":0,
            "limit":100
        },
    },#{"result":true}
    'deleteSoftPolicyCfg':
    {
        'action':'/api/hmsCfg/v1/deleteSoftPolicyCfg',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "policyCfgId":"1687762443325",
            "policyName":"auto222",
            "policyStatus":0,
            "downloadFlag":1,
            "triggerMode":0,
            "times":"2023-06-27 11:40",
            "softVersion":"BS5514_V1.20.20",
            "triggerType":"",
            "startTime":"",
            "endTime":"",
            "creatTime":"2023-06-26 15:54:03",
            "executes":"",
            "executeOrNot":0,
            "activateType":1,
            "timerActivateTime":"",
            "creatorID":"65bb5097-de07-44f7-ad5d-20cb413f60de",
            "creator":"root",
            "creatorUserInfo":{
                "userID":"65bb5097-de07-44f7-ad5d-20cb413f60de",
                "userName":"root",
                "userDomain":"1,2,3,4"
            },
            "enbPolicyCfgs":""},
    },#{"result":true}
    'activateSoftPolicyCfg':
    {
        'action':'/api/hmsCfg/v1/activateSoftPolicyCfg',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "policyCfgId":"1687769175745",
            "policyName":"1111",
            "policyStatus":1,
            "downloadFlag":1,
            "triggerMode":0,
            "times":"2023-06-26 15:10",
            "softVersion":"BS5514_V1.20.20",
            "triggerType":"",
            "startTime":"",
            "endTime":"",
            "creatTime":"2023-06-26 16:07:49",
            "executes":"",
            "executeOrNot":0,# 0-未执行 1-执行完成 2-执行中
            "activateType":1,
            "timerActivateTime":"",
            "creatorID":"65bb5097-de07-44f7-ad5d-20cb413f60de",
            "creator":"root",
            "creatorUserInfo":{
                "userID":"65bb5097-de07-44f7-ad5d-20cb413f60de",
                "userName":"root",
                "userDomain":"1,2,3,4"
            },
            "enbPolicyCfgs":""
        },
    },#{"result":true}
    'findPageTraceMeEnbs':
    {
        'action':'/api/hmsCfg/v1/findPageTraceMeEnbs',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "domainList":"1,2,3,4,5",
            "enbName":"",
            "enbIp":"",
            "serialNumber":"",
            "enbStatus":"",
            "switchState":"",
            "region":"",
            "delAccount":"",
            "start":0,
            "limit":100
        }
    },#dict
    'updateTraceMeParas':
    {
        'action':'/api/hmsCfg/v1/updateTraceMeParas',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "traceMeParas":[
                {
                    "serialNumber":"902181800017",
                    "enbId":39,
                    "switchState":"1",
                    "startTime":"2023-06-08 16:32:45",
                    "endTime":"2023-06-30 16:32:45",
                    "enbName":"Automatic-17"
                }
            ]
        }
    },#"result": 1
}