# coding = utf-8 
'''
Created on 2022年9月6日

@author: dj
'''
URL_DICT={
    'login':
    {
        'action':'/api/uiframe/v1/login Content-Type:application/json',
        'method':'POST',
        'header':{
            'content-type': "application/json; charset=UTF-8",
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; warningFlag=false'
        },
        'body':{
            'isEncypted':'true',
            'username':'root',
            'password':'hms123...',
            'vcode':'app'
        }
    },
    'queryVersionInfo':
    {
        'action':'/api/hmsCfg/v1/queryPageEnbWithVersionInfoByCondition',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'domainList':'1,2,3,5,7,9,11,13,15,17,19,21,23,25,27,3,5,7,9,11,13,15,17,19,21,2,3,5,7,9,11,13,15,17,19,21,23,25,273,25,27',
            'enbName':'',
            'serialNumber':'',
            'enbIp':'',
            'enbStatus':'',
            'region':'',
            'start':0,
            'limit':15
        }
    },
    'queryEnbSoftwareVersionFromDeviceBySns':
    {
        'action':'/api/hmsCfg/v1/queryEnbSoftwareVersionFromDeviceBySns',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "enbSns":["902272840016"]
            }
    },
    'downloadVersion':
    {
        'action':'/api/hmsCfg/v1/software/download',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'snList':[''],
            'softVersion':''
        }
    },
    'findPageDownloadTask':
    {
        'action':'/api/hmsCfg/v1/software/findPageDownloadTask',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"MultiUE4.9G-BT",
            "enbIp":"",
            "softVersion":"",
            "opStatus":"",
            "startTime":"",
            "endTime":"",
            "start":0,
            "limit":15
        }
    },
    'queryPageEnbByCondition4SoftwareDownload':
    {
        'action':'/api/hmsCfg/v1/software/queryPageEnbByCondition4SoftwareDownload',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "downloadVersion":"",
            "start":0,
            "limit":15
        },
    },
    'activeVersion':
    {
        'action':'/api/hmsCfg/v1/software/batchActivate',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'snList':[''],
        }
    },
    'findPageActivateTask':
    {
        'action':'/api/hmsCfg/v1/software/findPageActivateTask',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"MultiUE4.9G-BT",
            "enbIp":"",
            "softVersion":"",
            "opStatus":"",
            "startTime":"",
            "endTime":"",
            "start":0,
            "limit":15
        }
    },
    'rollbackVersion':
    {
        'action':'/api/hmsCfg/v1/software/batchRollback',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            'snList':[''],
        }
    },
    'findPageRollbackTask':
    {
        'action':'/api/hmsCfg/v1/software/findPageRollbackTask',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"MultiUE4.9G-BT",
            "enbIp":"",
            "softVersion":"",
            "opStatus":"",
            "startTime":"",
            "endTime":"",
            "start":0,
            "limit":15
        }
    },
    'batchRealtimeQuerySoftwareCtrlParameters':
    {
        'action':'/api/hmsCfg/v1/batchRealtimeQuerySoftwareCtrlParameters',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "enbList":[
                {
                    "enbId":141,
                    "placeId":1,
                    "enbIp":"193:168:6:0:100:700:0:1",
                    "connectionRequestUrl":"http://[193:168:6:0:100:700:0:1]:30005/",
                    "serialNumber":"902170700189",
                    "modelName":"BS5514",
                    "enbName":"baocai_new",
                    "enbStatus":0,
                    "enbLock":0,
                    "upStatus":0,
                    "softVersion":"BS5514_V1.10.60C1",
                    "hardVersion":"01.01.01.01.01",
                    "threeGPPSpecVersion":"TR181",
                    "specVersion":"",
                    "hardwarePlatform":"NXP",
                    "alarmStatus":2,
                    "manufacturer":"CHANGKUN",
                    "oui":"7C8334",
                    "creatTime":"2022-09-14 16:06:03",
                    "describes":"",
                    "delAccount":2,
                    "additionalSoftwareVersion":"",
                    "onLineTime":"2022-09-14 16:06:15",
                    "productClass":"L5W6-BS",
                    "wifiVersion":"",
                    "phyVersion":"",
                    "fpgaVersion":"",
                    "region":"",
                    "remark":"System Domain",
                    "domainName":""
                }
            ]
        }
    },
    'queryPageEnbByCondition4SoftwareRollback':
    {
        'action':'/api/hmsCfg/v1/software/queryPageEnbByCondition4SoftwareRollback',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "start":0,
            "limit":15
        }
    },
    'queryCellStatus':
    {
        'action':'/api/hmsCfg/v1/findPageCuCellStatus',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27",
            "enbName":"",
            "enbIp":"",
            "serialNumber":"",
            "region":"",
            "cellActiveState":"",
            "enbStatus":"",
            "start":0,
            "limit":15
        },
    },
    'updateDUCellBasic':
    {
        'action':'/api/hmsCfg/v1/updateDUCellBasic',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "enbId":21,
            "fapInstanceId":"1",
            "duCellBasicId":"1662540106391-1927208069",
            "cellId":"1",
            "nrDuCellName":"nrcell",
            "cellRadius":"500",
            "phyCellID":"133",
            "nRARFCNDL":"723324",
            "nRARFCNUL":"723324",
            "trackingAreaId":"0",
            "ssbFreqPos":"8752",
            "ssbTimePos":"128",
            "freqBandIndList":"79",
            "uLBandwidth":"12",
            "dLBandwidth":"12",
            "duplexMode":"1",
            "subcarrierSpacing":"1",
            "cyclicPrefix":"0",
            "slotAssignment":"2",
            "specialSlotStructure":"44",
            "taOffset":"1",
            "cellAdminState":"0",
            "ssbPeriodicityServingCell":"2",
            "sib1Period":"0",
            "ssbDescMethod":"1",
            "celAvailableState":"0",
            "smtcPeriod":"2",
            "smtcDuration":"3",
            "ranNotificationAreaId":"65535",
            "epre":"-15",
            "prachConfigurationIndex":"147",
            "zeroCorrelationZoneConfig":"7",
            "gpsOutClkDelWaitTime":"2592000"
        },
    },
    'realtimeQueryDuCellBasicByEnbId':
    {
        'action':'/api/hmsCfg/v1/realtimeQueryDuCellBasicByEnbId?enbId=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'findDuCellBasicByEnbId':
    {
        'action':'/api/hmsCfg/v1/findDuCellBasicByEnbId?enbId=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'batchRealTimeQueryCuCellStatus':
    {
        'action':'/api/hmsCfg/v1/batchRealTimeQueryCuCellStatus',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "cuCellIdentifierList":[{
                "enbId":16,
                "cuCellInstanceId":1
            }]
        },
    },
    'queryPageEnbByCondition':
    {
        'action':'/api/hmsCfg/v1/queryPageEnbByCondition',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "domainList":"1,3,5",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "start":0,
            "limit":15
        },
    },
    'findCuCellBasicByEnbId':
    {
        'action':'/api/hmsCfg/v1/findCUCellBasicByEnbId?enbId=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'updateCUCellBasic':
    {
        'action':'/api/hmsCfg/v1/updateCUCellBasic',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
            "cuCellBasicId":"16625316903451085107142",
            "enbId":31,
            "fapInstanceId":"1",
            "cellId":"0",
            "cellName":"nrcell",
            "cuFrequencyBand":"79",
            "duplexMode":"1",
            "userLabel":"hlt",
            "cellActiveState":"0",
            "cellAvailableState":"0"
        },
    },
    'findPageSoftWareInfo':
    {
        'action':'/api/hmsCfg/v1/findPageSoftWareInfo?softVersion=',
        'method':'GET',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'reboot':
    {
        'action':'/api/hmsCfg/v1/rebootAsync?enbIdStr=',
        'method':'POST',
        'header':{
            'content-type':'application/json;charset=UTF-8',
            'Cookie':'lang=en-US; warningFlag=false; BAYEUX_BROWSER=as0hxfztixv81uxu; sessioncode=yd97jwdao3; username=root'
        },
        'body':{
        },
    },
    'uploadSoft':
    {
        'action':'/api/hmsCfg/v1/uploadSoft?fileSize=',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            'manufacturer':'',
            'softVersion':'',
            'model':'',
            'descInfo':'',
        },
    },
    'uploadDataFileXml':
    {
        'action':'/api/hmsCfg/v1/uploadDataFileXml',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
            "enbId":15,
            "placeId":1,
            "enbIp":"193:168:6:0:200::1",
            "connectionRequestUrl":"http://[193:168:6:0:200::1]:30005/",
            "serialNumber":"902272840007",
            "modelName":"BS5514",
            "enbName":"Automatic-18",
            "enbStatus":0,
            "enbLock":0,
            "upStatus":0,
            "softVersion":"BS5514_V1.10.80P1",
            "hardVersion":"01.01.01.01.04",
            "threeGPPSpecVersion":"TR181",
            "specVersion":"",
            "hardwarePlatform":"NXP",
            "alarmStatus":2,
            "manufacturer":"CHANGKUN",
            "oui":"7C8334",
            "creatTime":"2022-11-03 15:23:56",
            "describes":"自动化测试V4",
            "delAccount":2,
            "additionalSoftwareVersion":"",
            "onLineTime":"2022-11-09 16:10:02",
            "productClass":"L5W6-BS",
            "wifiVersion":"",
            "phyVersion":"",
            "fpgaVersion":"",
            "region":"",
            "remark":"System Domain",
            "domainName":""
        }],
    },
    'queryPageEnbWithDataFileSyncStatusByCondition':
    {
        'action':'/api/hmsCfg/v1/queryPageEnbWithDataFileSyncStatusByCondition',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "domainList":"1,2,3,5,7,9,11,13,15,17,19,21,23,25,27,4,5,7,8",
            "enbName":"",
            "enbIp":"",
            "softVersion":"",
            "serialNumber":"",
            "enbStatus":"",
            "region":"",
            "delAccount":"",
            "start":0,
            "limit":15
        },
    },
    'findEnbDataFile':
    {
        'action':'/api/hmsCfg/v1/findEnbDataFile?enbId=',
        'method':'GET',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
        },
    },
    'downloadXmlFileToLocal':
    {
        'action':'/api/httpfs/v1/download?',
        'method':'GET',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
        },
    },
    'uploadXmlDataFile':
    {
        'action':'/api/hmsCfg/v1/uploadDataFile?',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
        },
    },
    'queryPageDataFile':
    {
        'action':'/api/hmsCfg/v1/queryPageDataFile',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':{
            "domainList":"1,3,5",
            "enbName":"",
            "enbIp":"",
            "serialNumber":"",
            "enbStatus":"",
            "dataFileActivateStatus":"",
            "delAccount":"",
            "start":0,
            "limit":15
        }
    },
    'deleteDataFileByIds':
    {
        'action':'/api/hmsCfg/v1/deleteDataFileByIds',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[
            "1668048369485872874821"
        ]
    },
    'downloadDataFileToGnb':
    {
        'action':'/api/hmsCfg/v1/downloadDataFile',
        'method':'POST',
        'header':{
            'Cookie':'lang=en-US; BAYEUX_BROWSER=1myku1tiv3o1t1if; sessioncode=uxplximbon; username=root; warningFlag=false'
        },
        'body':[{
            "dataId":"1667987649609-1854837404",
            "serialNumber":"902272840007",
            "fileName":"Automatic-18_902272840007_20221109184508.cfg"
        }],
    },
}